<script setup lang="ts">
// https://checkout-qa.geins.services/eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJjYXJ0SWQiOiI0NjUxOTBlNC03M2UyLTQyNjEtOGI4ZC1iMzMxYWIzZTBhNDYiLCJ1c2VyIjp7ImlkIjowLCJlbWFpbCI6ImFydmlkc3NvbkBnZWlucy5pbyIsImN1c3RvbWVyVHlwZSI6IlBFUlNPTiIsImFkZHJlc3MiOnsiZmlyc3ROYW1lIjoiS3Jpc3RpYW4iLCJsYXN0TmFtZSI6IkFydmlkc3NvbiIsImNvbXBhbnkiOiIiLCJtb2JpbGUiOiIiLCJwaG9uZSI6IiIsImNhcmVPZiI6IiIsImVudHJ5Q29kZSI6IiIsImFkZHJlc3NMaW5lMSI6Ik1hbG1za2lsbG5hZHNnYXRhbiA0NGEiLCJhZGRyZXNzTGluZTIiOiIiLCJhZGRyZXNzTGluZTMiOiIiLCJ6aXAiOiIxMTEgNTciLCJjaXR5IjoiU3RvY2tob2xtIiwic3RhdGUiOiIiLCJjb3VudHJ5IjoiU0UifX0sInNldHRpbmdzIjp7InBheW1lbnRJZCI6MjMsInNoaXBwaW5nSWQiOjAsImN1c3RvbWVyVHlwZSI6IlBFUlNPTiJ9LCJnZWluc1NldHRpbmdzIjp7ImVudmlyb25tZW50IjoicHJvZCIsImFwaUtleSI6IkJENjc5RkYwLTA1QkUtNDg3Ni1CNTRDLUYxNkRGREI4RTk2NyIsImFjY291bnROYW1lIjoibGFicyIsImNoYW5uZWwiOiIxIiwidGxkIjoic2UiLCJsb2NhbGUiOiJzdi1TRSIsIm1hcmtldCI6InNlIn19.
const token = 'eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJjYXJ0SWQiOiI0NjUxOTBlNC03M2UyLTQyNjEtOGI4ZC1iMzMxYWIzZTBhNDYiLCJ1c2VyIjp7ImlkIjowLCJlbWFpbCI6ImFydmlkc3NvbkBnZWlucy5pbyIsImN1c3RvbWVyVHlwZSI6IlBFUlNPTiIsImFkZHJlc3MiOnsiZmlyc3ROYW1lIjoiS3Jpc3RpYW4iLCJsYXN0TmFtZSI6IkFydmlkc3NvbiIsImNvbXBhbnkiOiIiLCJtb2JpbGUiOiIiLCJwaG9uZSI6IiIsImNhcmVPZiI6IiIsImVudHJ5Q29kZSI6IiIsImFkZHJlc3NMaW5lMSI6Ik1hbG1za2lsbG5hZHNnYXRhbiA0NGEiLCJhZGRyZXNzTGluZTIiOiIiLCJhZGRyZXNzTGluZTMiOiIiLCJ6aXAiOiIxMTEgNTciLCJjaXR5IjoiU3RvY2tob2xtIiwic3RhdGUiOiIiLCJjb3VudHJ5IjoiU0UifX0sInNldHRpbmdzIjp7InBheW1lbnRJZCI6MjMsInNoaXBwaW5nSWQiOjAsImN1c3RvbWVyVHlwZSI6IlBFUlNPTiJ9LCJnZWluc1NldHRpbmdzIjp7ImVudmlyb25tZW50IjoicHJvZCIsImFwaUtleSI6IkJENjc5RkYwLTA1QkUtNDg3Ni1CNTRDLUYxNkRGREI4RTk2NyIsImFjY291bnROYW1lIjoibGFicyIsImNoYW5uZWwiOiIxIiwidGxkIjoic2UiLCJsb2NhbGUiOiJzdi1TRSIsIm1hcmtldCI6InNlIn19.';

const router = useRouter();
onMounted(() => {
    router.push(`/v0/${token}`);
})

</script>
<template>
    <div class="flex min-h-screen items-center justify-center">
        <p>Geins Checkout</p>
    </div>
</template>
