name: CI Release Next to Azure SWA
on:
  push:
    branches:
      - next

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      GEINS_DEBUG: ${{ vars.GEINS_DEBUG_QA }}
      NITRO_PRESET: ${{ vars.NITRO_PRESET_AZURE_SWA }}
      LATEST_VERSION: ${{ vars.LATEST_VERSION_QA }}
      BASE_URL: ${{ vars.BASE_URL_QA }}
      PRODUCT_IMAGE_DOMAIN: ${{ vars.PRODUCT_IMAGE_DOMAIN_QA }}
      PRODUCT_IMAGE_BASE_URL: ${{ vars.PRODUCT_IMAGE_BASE_URL_QA }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_SEA_0BEE71803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_build_command: 'yarn build'
          app_location: '/' # App source code path
          api_location: '.output/server' # Api source code path - optional
          output_location: '.output/public' # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
